### ISSUE TITLE
Optimize Featured Image

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.behavior.featuredimage#25]
It would be a good idea to optimize the PNG image before storing it in the field.

We can use [imagemin](https://www.npmjs.com/package/imagemin) package the same way it is used in the development buildout.

**Comment by rodfersou** [comment]
Fine, I think we just need to add [optipng](https://github.com/imagemin/imagemin-optipng/blob/master/package.json#L46) command in our `buildout` `node` `recipe` to add a new command into `PATH`, then call `optipng` into this image with [subprocess module](https://docs.python.org/2/library/subprocess.html) (maybe we need to use a temporary file for this to work).

```
$ optipng --help
Synopsis:
    optipng [options] files ...
Files:
    Image files of type: PNG, BMP, GIF, PNM or TIFF
Basic options:
    -?, -h, -help       show this help
    -o <level>          optimization level (0-7)                [default: 2]
    -v                  run in verbose mode / show copyright and version info
General options:
    -backup, -keep      keep a backup of the modified files
    -clobber            overwrite existing files
    -fix                enable error recovery
    -force              enforce writing of a new output file
    -preserve           preserve file attributes if possible
    -quiet, -silent     run in quiet mode
    -simulate           run in simulation mode
    -out <file>         write output file to <file>
    -dir <directory>    write output file(s) to <directory>
    -log <file>         log messages to <file>
    --                  stop option switch parsing
Optimization options:
    -f <filters>        PNG delta filters (0-5)                 [default: 0,5]
    -i <type>           PNG interlace type (0-1)
    -zc <levels>        zlib compression levels (1-9)           [default: 9]
    -zm <levels>        zlib memory levels (1-9)                [default: 8]
    -zs <strategies>    zlib compression strategies (0-3)       [default: 0-3]
    -zw <size>          zlib window size (256,512,1k,2k,4k,8k,16k,32k)
    -full               produce a full report on IDAT (might reduce speed)
    -nb                 no bit depth reduction
    -nc                 no color type reduction
    -np                 no palette reduction
    -nx                 no reductions
    -nz                 no IDAT recoding
Editing options:
    -snip               cut one image out of multi-image or animation files
    -strip <objects>    strip metadata objects (e.g. "all")
Optimization levels:
    -o0         <=>     -o1 -nx -nz                             (0 or 1 trials)
    -o1         <=>     -zc9 -zm8 -zs0 -f0                      (1 trial)
                (or...) -zc9 -zm8 -zs1 -f5                      (1 trial)
    -o2         <=>     -zc9 -zm8 -zs0-3 -f0,5                  (8 trials)
    -o3         <=>     -zc9 -zm8-9 -zs0-3 -f0,5                (16 trials)
    -o4         <=>     -zc9 -zm8 -zs0-3 -f0-5                  (24 trials)
    -o5         <=>     -zc9 -zm8-9 -zs0-3 -f0-5                (48 trials)
    -o6         <=>     -zc1-9 -zm8 -zs0-3 -f0-5                (120 trials)
    -o7         <=>     -zc1-9 -zm8-9 -zs0-3 -f0-5              (240 trials)
    -o7 -zm1-9  <=>     -zc1-9 -zm1-9 -zs0-3 -f0-5              (1080 trials)
Notes:
    The combination for -o1 is chosen heuristically.
    Exhaustive combinations such as "-o7 -zm1-9" are not generally recommended.
Examples:
    optipng file.png                                            (default speed)
    optipng -o5 file.png                                        (slow)
    optipng -o7 file.png                                        (very slow)
```

**Comment by rodfersou** [comment]
There is an issue to use `STDIN` and `STDOUT` into this program.  Fortunatelly, [ameyp already did a fork](https://github.com/ameyp/optipng-stream-bin) to make it work with these streams.  This way we don't need to create a temporary file.

**Comment by hvelarde** [comment]
I just made a test and it confirms we need to optimize the resulting image:

![screen shot 2016-03-14 at 12 49 13](https://cloud.githubusercontent.com/assets/341393/13750247/71004058-e9e3-11e5-87d4-4ae373b21289.png)

**Comment by rodfersou** [comment]
This could be another option https://github.com/keul/collective.optimage

**Comment by hvelarde** [comment]
@keul what's the status of that package? are you using it in production? have you though on updating it to use Node.js plugins?

**Comment by keul** [comment]
@hvelarde no, I developed it only for exploring the possibility to have this feature but I never used anywhere in production. It must probably be refactored for using some queue system... at that time plone.app.async and celery were not there.

I can move it on collective if you want to keep working on it.

**Comment by hvelarde** [comment]
@keul I think that's a good idea; we could start without queue system, test it in production and add support for [collective.taskqueue](https://github.com/collective/collective.taskqueue) in the future, if needed.

but let us take a look first; sometimes is easier to start over that to make a huge refactor.

**Comment by keul** [comment]
@hvelarde done. You are now maintainer on pypi also.
